config/routes.rb
Got::Application.routes.draw do
  resources :game_versions, only: [:index]
  resources :games, only: [:index, :new, :create, :update, :edit] do
    resources :results, except: [:index]
  end
  resources :houses, only: [:index]
  resources :players, only: [:index, :show]

  root 'pages#init'
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :results, dependent: :destroy
  belongs_to :game_version

  validates :date, presence: true
  validates :game_version_id, presence: true
end

app/models/game_version.rb
class GameVersion < ActiveRecord::Base
  has_many :games, dependent: :restrict

  def name_with_capacity
    "#{name} (#{min_players}-#{max_players})"
  end
end

app/models/house.rb
class House < ActiveRecord::Base
  has_many :results, dependent: :restrict
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :results, dependent: :restrict
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :game
  belongs_to :house
  belongs_to :player

  validates :game_id, presence: true
  validates :house_id, presence: true, uniqueness: { scope: :game_id }
  validates :player_id, presence: true, uniqueness: { scope: :game_id }
  validates :position, presence: true, uniqueness: { scope: :game_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/game_versions_controller.rb
class GameVersionsController < ApplicationController
  respond_to :json

  expose(:game_versions)

  def index
    render json: game_versions.extend(GameVersionsRepresenter)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :json

  expose(:games) { Game.includes(results: [:house, :player]).includes(:game_version) }
  expose(:game, attributes: :game_params)
  expose(:default_game_version) { GameVersion.first }

  def index
    render json: games.extend(GamesRepresenter)
  end

  def new
    game.game_version = default_game_version

    render json: game.extend(NewGameRepresenter)
  end

  def edit
    render json: game.extend(GameRepresenter)
  end

  def create
    game.save

    respond_with game, represent_with: GameRepresenter
  end

  def update
    game.save

    respond_with game, represent_with: GameRepresenter
  end

  private

  def game_params
    params.require(:game).permit(:number, :date, :game_version_id, :comment)
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  respond_to :json

  expose(:houses)

  def index
    render json: houses.extend(HousesRepresenter)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  expose(:players) { Player.includes(:results).order(name: :asc) }
  expose(:player)

  def index
    render json: players.extend(PlayersRepresenter)
  end

  def show
    render json: player.extend(PlayerRepresenter)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  respond_to :json

  expose(:game)
  expose(:results) { game.results }
  expose(:result, attributes: :result_params)

  def new
    result.position = game.results.count + 1

    render json: result.extend(ResultRepresenter)
  end

  def create
    result.save

    respond_with result, location: [game, result], represent_with: ResultRepresenter
  end

  def update
    result.save

    respond_with [game, result]
  end

  private

  def result_params
    params.require(:result).permit(:house_id, :player_id, :position, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/edit.html.slim
h1 Podaj wyniki

= simple_form_for game, url: game_path(game), method: :put do |f|
  = f.input :number
  = f.input :date, as: :date, end_year: Date.today.year
  = f.input :game_version_id, collection: GameVersion.all, label_method: :name_with_capacity
  = f.input :comment
  = f.button :submit

app/views/games/new.html.slim
h1 Podaj wyniki

= simple_form_for game, url: games_path do |f|
  = f.input :number
  = f.input :date, as: :date, end_year: Date.today.year
  = f.input :game_version_id, collection: GameVersion.all, label_method: :name_with_capacity
  = f.input :comment
  = f.button :submit

app/views/games/show.html.slim
h1 ##{game.number} - #{game.date}
h3= game.game_version.name_with_capacity

- if game.comment
  p= game.comment

table
  tr
    th #
    th House
    th Player
    th Comment
    th Akcja
  - game.results.order(position: :asc).each do |result|
    tr
      td= result.position
      td= result.house.name
      td= result.player.name
      td= result.comment
      td= link_to 'Edytuj', [:edit, game, result]

= link_to 'Dodaj wynik', new_game_result_path(game)
= link_to 'Wszystkie gry', root_path

app/views/init/index.html.slim
.init ng-controller="GamesCtrl"
  | Loading...

app/views/layouts/application.html.slim
doctype html
html ng-app="got" lang="pl"
  head
    meta charset="utf-8"
    title GoT Stats

    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tags
  body
    .Grid
      header.Header
        h1 Winter is Comming
        nav.Nav
          = link_to t('nav.home'), "##{root_path}", class: 'Nav__item'
          = link_to t('nav.players'), "##{players_path}", class: 'Nav__item'

      - unless flash.empty?
        section.Flash
          - [:notice, :success, :alert].each do |key|
            - if flash.key?(key)
              div class="Flash__message--#{key}"= flash[key]

      .site
        = yield

  = javascript_include_tag "application"

app/views/pages/init.html.slim
<ng-view></ng-view>

app/views/players/index.html.slim
section ng-controller="PlayersCtrl"
  table
    thead
      tr
        th= t('players.name')
        th= t('players.games')
        th= t('players.avg_position')
    tbody
      tr ng-repeat="player in players"
        td ng-bind="player.name"
        td ng-bind="player.games_count"
        td ng-bind="player.avg_position"

app/views/players/show.html.slim
.Player ng-controller="PlayerCtrl"
  h1 ng-bind="player.name"

app/views/results/edit.html.slim
h1 Podaj wyniki

= simple_form_for [game, result], method: :put do |f|
  = f.association :house, collection: House.all(order: :name)
  = f.association :player, collection: Player.all(order: :name)
  = f.input :position, collection: 1..9
  = f.input :comment
  = f.button :submit